version: 2

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

builds:
  - id: server
    main: ./cmd/server
    binary: main
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
      - GOFLAGS=-buildvcs=false
    flags:
      - -trimpath
      - -a
      - -installsuffix=cgo

release:
  gitlab:
    owner: yodamad-workshops
    name: easylab
  draft: false
  prerelease: auto
  make_latest: true
  replace_existing_draft: true
  name_template: '{{ .Tag }}'
  header: |

  footer: |
    ## Enjoy 👨🏻‍🔬 👩🏼‍🔬
    📆 {{ .Now.Format "2006-01-02" }} - Copyright @yodamad
