apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "easylab.fullname" . }}-jobs-pvc
  namespace: {{ include "easylab.namespace" . }}
  labels:
    {{- include "easylab.labels" . | nindent 4 }}
    component: jobs-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.jobs.size }}
  {{- if .Values.persistence.jobs.storageClass }}
  storageClassName: {{ .Values.persistence.jobs.storageClass | quote }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "easylab.fullname" . }}-data-pvc
  namespace: {{ include "easylab.namespace" . }}
  labels:
    {{- include "easylab.labels" . | nindent 4 }}
    component: data-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
  {{- end }}
