{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "easylab.fullname" . }}-secrets
  namespace: {{ include "easylab.namespace" . }}
  labels:
    {{- include "easylab.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.adminPassword }}
  LAB_ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
  {{- end }}
  {{- if .Values.secrets.studentPassword }}
  LAB_STUDENT_PASSWORD: {{ .Values.secrets.studentPassword | quote }}
  {{- end }}
  {{- with .Values.secrets.ovh }}
  {{- if .applicationKey }}
  OVH_APPLICATION_KEY: {{ .applicationKey | quote }}
  {{- end }}
  {{- if .applicationSecret }}
  OVH_APPLICATION_SECRET: {{ .applicationSecret | quote }}
  {{- end }}
  {{- if .consumerKey }}
  OVH_CONSUMER_KEY: {{ .consumerKey | quote }}
  {{- end }}
  {{- if .serviceName }}
  OVH_SERVICE_NAME: {{ .serviceName | quote }}
  {{- end }}
  {{- if .endpoint }}
  OVH_ENDPOINT: {{ .endpoint | quote }}
  {{- end }}
  {{- end }}
{{- end }}
