apiVersion: v1
kind: Service
metadata:
  name: {{ include "easylab.fullname" . }}-service
  namespace: {{ include "easylab.namespace" . }}
  labels:
    {{- include "easylab.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "easylab.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
