apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: easylab-jobs-pvc
  namespace: easylab
  labels:
    app: easylab
    component: jobs-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: easylab-data-pvc
  namespace: easylab
  labels:
    app: easylab
    component: data-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: longhorn
