apiVersion: v1
kind: Secret
metadata:
  name: easylab-secrets
  namespace: easylab
  labels:
    app: easylab
    component: secrets
type: Opaque
stringData:
  # OVH credentials - replace with your actual values
  OVH_APPLICATION_KEY: "a2398ee51ce05a8b"
  OVH_APPLICATION_SECRET: "d9670bfc3a0025d9d69d1e704210996e"
  OVH_CONSUMER_KEY: "4fb9644072de74c0a5744e5c4f5941ce"
  OVH_SERVICE_NAME: "8982c1644daa41309a0255e464d26d6d"
  OVH_ENDPOINT: "ovh-eu"  # or ovh-ca, ovh-us depending on your region
  # Override default passwords in production
  LAB_ADMIN_PASSWORD: "SuperAdmin"
  LAB_STUDENT_PASSWORD: "Snowcamp2026"
