apiVersion: v2
name: easylab-helm
description: A Helm chart for deploying EasyLab — a lab-as-code platform that provisions cloud-based lab environments
type: application
version: 0.0.0-dev
appVersion: "0.0.0-dev"
dependencies:
  - name: traefik
    version: "41.4.0"
    repository: https://traefik.github.io/charts
    condition: traefik.enabled
  - name: cert-manager
    version: "v1.21.1"
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled

maintainers:
  - name: yodamad
keywords:
  - easylab
  - lab
  - workshop
  - kubernetes
  - coder
home: https://gitlab.com/yodamad-workshops/easylab
sources:
  - https://gitlab.com/yodamad-workshops/easylab
